## See more docs at https://docs.gitea.io/en-us/install-with-docker/  or  https://docs.gitea.io/en-us/config-cheat-sheet/
version: "3.5"

services:
    postgres:
        container_name: gitea-postgres-9.5
        image: postgres:9.5
        environment:
            - POSTGRES_USER=gitea
            - POSTGRES_PASSWORD=gitea
            - POSTGRES_DB=gitea
        restart: unless-stopped
        volumes:
            - postgres:/var/lib/postgresql/data
    gitea:
        container_name: gitea-app-1.3.3
        image: gitea/gitea:1.3.3
        depends_on:
            - postgres
        environment:
            - RUN_CROND=true
        links:
            - postgres
        ports:
            - 127.0.0.1:3000:3000
            - 127.0.0.1:3022:3022
        restart: unless-stopped
        volumes:
            - data:/data

volumes:
    postgres:
    data:
