## See more docs at https://docs.gitlab.com/omnibus/docker/README.html  or  https://docs.gitlab.com/omnibus/gitlab-mattermost/
version: "3.5"

services:
    gitlab:
        container_name: gitlab-ce-10.5.4-ce.0
        image: gitlab/gitlab-ce:10.5.4-ce.0
        hostname: 'localhost'
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'http://127.0.0.1'
                gitlab_rails['gitlab_shell_ssh_port'] = 9022
                mattermost_external_url 'http://localhost'
        ports:
            - 127.0.0.1:80:80
            - 127.0.0.1:9022:22
        restart: always
        volumes:
            - config:/etc/gitlab
            - data:/var/opt/gitlab
            - logs:/var/log/gitlab

volumes:
    config:
    data:
    logs:
