## See more docs at https://hub.docker.com/r/atlassian/bitbucket-server/
version: "3.5"

services:
    bitbucket:
        container_name: bitbucket-5.8.1
        image: atlassian/bitbucket-server:5.8.1
        ports:
            - 127.0.0.1:7990:7990
            - 127.0.0.1:7999:7999
        restart: always
        volumes:
            - data:/var/atlassian/application-data/bitbucket

volumes:
    data:
